version: '3'

services:
  flask_app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    restart: always

  db:
    image: postgres
    environment:
      POSTGRES_USER: devops
      POSTGRES_PASSWORD: Asd12345
      POSTGRES_DB: flask-db
    volumes:
      - /home/data1:/var/lib/postgresql/data

volumes:
  data:
